on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Script
        run: |
          npm install
          npm run build-release
      - name: Buat Rilis Baru
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1
          name: Acode Kotlin Language Server
          files: ./dist.zip
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
